# HW8: Arrays and Loops

## Problem 1

Import Numpy 

a) Create an array of 50 ones called $x$.

In [289]:
import numpy as np
x = np.ones((50))
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

b) Create an array from 1-20 with 50 equally-spaced elements two different ways (using a loop and a single command). Call the two arrays $y$ and $z$.

In [454]:
y = np.linspace(1, 20, 50)
newy = y.reshape(10,5)
print(newy)

[[ 1.          1.3877551   1.7755102   2.16326531  2.55102041]
 [ 2.93877551  3.32653061  3.71428571  4.10204082  4.48979592]
 [ 4.87755102  5.26530612  5.65306122  6.04081633  6.42857143]
 [ 6.81632653  7.20408163  7.59183673  7.97959184  8.36734694]
 [ 8.75510204  9.14285714  9.53061224  9.91836735 10.30612245]
 [10.69387755 11.08163265 11.46938776 11.85714286 12.24489796]
 [12.63265306 13.02040816 13.40816327 13.79591837 14.18367347]
 [14.57142857 14.95918367 15.34693878 15.73469388 16.12244898]
 [16.51020408 16.89795918 17.28571429 17.67346939 18.06122449]
 [18.44897959 18.83673469 19.2244898  19.6122449  20.        ]]


In [444]:
z = np.array([(1+i*(19/49)) for i in range(0,50)])
newz = z.reshape(10, 5) 
print(newz)

[[ 1.          1.3877551   1.7755102   2.16326531  2.55102041]
 [ 2.93877551  3.32653061  3.71428571  4.10204082  4.48979592]
 [ 4.87755102  5.26530612  5.65306122  6.04081633  6.42857143]
 [ 6.81632653  7.20408163  7.59183673  7.97959184  8.36734694]
 [ 8.75510204  9.14285714  9.53061224  9.91836735 10.30612245]
 [10.69387755 11.08163265 11.46938776 11.85714286 12.24489796]
 [12.63265306 13.02040816 13.40816327 13.79591837 14.18367347]
 [14.57142857 14.95918367 15.34693878 15.73469388 16.12244898]
 [16.51020408 16.89795918 17.28571429 17.67346939 18.06122449]
 [18.44897959 18.83673469 19.2244898  19.6122449  20.        ]]


c) Subtract $y$ from $z$ and report the sum of the absolute difference of each element to show that they are the same.

In [451]:
k = y - z
print(k)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [458]:
print("difference = ",(sum(k)))

difference =  0.0


## Problem 2

import the python package "random"

a) Create a matrix, $M$, as a 1x1 numpy array of value 1

In [459]:
M = np.ones(1)

In [461]:
print(M)

[1.]


b) Using a while loop, append a random integer between 1 and 10 to the end of matrix $M$ until the last element is a 7.

In [474]:
M = np.ones(1)
x= 1
while x!= 7:
    x= random.randrange(1,10)
    M= np.append(M,x)
    
print(M)



[1. 5. 8. 2. 9. 1. 2. 3. 3. 4. 7.]


c) Report the number of elements in $M$ and the mean value of the elements after the loop.

In [479]:
print("number of elements",np.size(M))
print("mean value after loop",np.mean(M))

number of elements 13
mean value after loop 3.4615384615384617


d) Also, because a while loop is easily susceptible to infinite loops, create a variable $i$ to keep track of how many times you have gone through the while loop. If $i$ exceeds 30, immediately exit the while loop. Don't report the matrix size using $i$.

You may need to search online (e.g. Google) how to create a random integer using the random package and how to append elements to a numpy array. 

In [480]:
M = np.ones(1)
x= 1
i= 0
while x!= 7:
    i= i+1
    x= random.randrange(1,10)
    M= np.append(M,x)
    if i == 30:
        print("Loop ended after 30 iterations")
        break  
print("M=",M)
print("i=",i)
print("number of elements",np.size(M))

print("mean value after loop",np.mean(M))

M= [1. 8. 4. 9. 9. 7.]
i= 5
number of elements 6
mean value after loop 6.333333333333333


## Problem 3

Using the following array, $a$:

Reshape the array to a 5x5 matrix (using a numpy command)

Loop through each element of the array. If the element value is 5 or 8, print the element index. Also, keep track of how many 5s and 8s there are with variable $k$. Print $k$. If the element value is a 1, print "You win!"

In [481]:
a = np.array([  8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1.,4.,5.,6.,6.])

In [482]:
newa = a.reshape(5, 5) 
print(newa)

[[ 8.  3. 10.  8.  2.]
 [ 2. 10. 10.  5. 10.]
 [ 2. 10.  9. 10.  9.]
 [ 4.  2.  8.  7.  4.]
 [ 1.  4.  5.  6.  6.]]


In [483]:
print(newa)
rc=np.shape(newa)
row=rc[0]
colum=rc[1]

k=0

for i in range(0,row):
    for j in range(0,colum):
        if newa[i,j] == 5:
            k= k+1
            print("Element value 5 at position [",i,",",j,"]")
        elif newa[i,j] == 8:
            k= k+1
            print("Element value 8 at position  [",i,",",j,"]")
        elif newa[i,j] == 1:
            print("Element value 1 at [",i,",",j,"] You Win!")
            
print("Number of 5's & 8's in Array =",k)

[[ 8.  3. 10.  8.  2.]
 [ 2. 10. 10.  5. 10.]
 [ 2. 10.  9. 10.  9.]
 [ 4.  2.  8.  7.  4.]
 [ 1.  4.  5.  6.  6.]]
Element value 8 at position  [ 0 , 0 ]
Element value 8 at position  [ 0 , 3 ]
Element value 5 at position [ 1 , 3 ]
Element value 8 at position  [ 3 , 2 ]
Element value 1 at [ 4 , 0 ] You Win!
Element value 5 at position [ 4 , 2 ]
Number of 5's & 8's in Array = 5


## Problem 4

For the following arrays (matrices and vectors):

A = \begin{bmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{bmatrix}

x = \begin{bmatrix}
1\\ 
3\\ 
4
\end{bmatrix}

B = \begin{bmatrix}
-0.1 & -0.2 & -0.3\\ 
3 & 10 & 2\\ 
4 & 2 & 0.5
\end{bmatrix} 

Perform the following operations:

a) $A \circ B$ (element-wise multiplication)

In [484]:
A = [[1,2,3],
    [4,5,6],
    [7,8,9]]
B = [[-.1,-.2,-.3],
    [3,10,2],
    [4,2,.5]]
x = [[1],[3],[4]]

print(np.multiply(A, B))


[[-0.1 -0.4 -0.9]
 [12.  50.  12. ]
 [28.  16.   4.5]]


b) $A \bullet B$ (dot product multiplication)

In [485]:
print(np.dot(A,B))

[[17.9 25.8  5.2]
 [38.6 61.2 11.8]
 [59.3 96.6 18.4]]


c) $A \times B$ (cross product multiplication)

In [486]:
print(np.cross(A,B))

[[ 1.11022302e-16 -5.55111512e-17  0.00000000e+00]
 [-5.00000000e+01  1.00000000e+01  2.50000000e+01]
 [-1.40000000e+01  3.25000000e+01 -1.80000000e+01]]


d) $A \bullet x$

In [487]:
print(np.dot(A,x))

[[19]
 [43]
 [67]]


e) $A^{-1} \bullet B$

In [488]:
print(np.dot(inv(A),B))

[[-6.62029145e+15 -5.73758593e+16 -1.19795750e+16]
 [ 1.32405829e+16  1.14751719e+17  2.39591500e+16]
 [-6.62029145e+15 -5.73758593e+16 -1.19795750e+16]]
